# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Working Title

author:
  name:           'Benjamin Trent'

paginate:         5
plugins: [jekyll-paginate]
# Custom vars

github:
  repo:           https://github.com/computician
